version: '3.8'

services:
    # web server
    nginx:
        container_name: ${APP_NAME}_nginx-${VERSION}
        build: docker/nginx
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ${SRC_PATH}:/var/www/html
            - ./docker/nginx/logs:/var/log/nginx
        ports:
            - 8000:8000
        restart: always

    # backend
    php:
        container_name: ${APP_NAME}_php-${VERSION}
        build: docker/php
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ${SRC_PATH}:/var/www/html
        restart: always

    # DB server
    mysql:
        container_name: ${APP_NAME}_mysql-${VERSION}
        image: mysql:8.0
        ports:
            - 13306:3306
        environment:
            MYSQL_ROOT_PASSWORD: p@ssw0rd
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Asia/Tokyo
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/mysql/logs:/var/log/mysql
            - ./docker/mysql/sql:/docker-entrypoint-initdb.d
        restart: always

    # DB client
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        links:
            - mysql
        ports:
            - 8580:80
        volumes:
            - /sessions

volumes:
    php-fpm-socket:
